"""Tests for drift_report.py -- DRP-001 to DRP-019 over the golden and tree fixtures.

Invocation: test
Lifecycle: active

Rules: .claude/references/general/drift-report.md (DRP-NNN) and drift-metric.md (DRM-NNN).
Golden: fixtures/drift/casos.json (plan-000008; read-only). Trees: fixtures/drift_report/<case>/
(esperado.json written by hand, per case, not generated by the calculator).
"""

from __future__ import annotations

import json
from pathlib import Path

import drift_report as dr
import pytest

_TESTS_DIR = Path(__file__).resolve().parent
_FIX = _TESTS_DIR / "fixtures" / "drift_report"
_GOLDEN = _TESTS_DIR / "fixtures" / "drift" / "casos.json"

GOLDEN = json.loads(_GOLDEN.read_text(encoding="utf-8"))["casos"]
CASES = sorted(p.parent.name for p in _FIX.glob("*/esperado.json"))
SLUG = "contas-da-semana"
STEPS = ("D1", "D2", "D3a", "D3b")


def stub_status(root, slug):
    """Simulated `check_specify.py --status`: the case's status.txt."""
    return (Path(root) / "status.txt").read_text(encoding="utf-8").strip()


def make_report(name, **kw):
    root = _FIX / name
    exp = json.loads((root / "esperado.json").read_text(encoding="utf-8"))
    plan = root / "plan.md"
    return exp, dr.generate(
        root, SLUG, plan=plan if plan.is_file() else None, moment=exp.get("momento", "M2"),
        status_fn=kw.pop("status_fn", stub_status), **kw)


def check_case(rep, exp):
    if exp.get("nao_aplicavel"):
        assert rep.get("nao_aplicavel") is True
        assert rep["razao_nm"] == exp["razao_nm"]
        assert rep.get("motivo") == exp.get("motivo")
        return
    for step, want in exp["degraus"].items():
        got = rep["degraus"][step]
        for field, value in want.items():
            assert got[field] == value, f"{step}.{field}"
    for field, value in exp.get("leituras", {}).items():
        assert rep["leituras"][field] == value, f"leituras.{field}"
    assert rep["ressalvas"] == exp["ressalvas"]
    for field, value in exp.get("auditoria", {}).items():
        assert rep["auditoria"][field] == value, f"auditoria.{field}"
    if "d0" in exp:
        d0 = rep["leituras"]["d0"]
        assert (d0["estado"], d0["frases"], [r["frase"] for r in d0["residuo"]]) == (
            exp["d0"]["estado"], exp["d0"]["frases"], exp["d0"]["residuo"])
    if "intencao_sem_feature" in exp:
        got = rep["leituras"]["intencao_sem_feature"]
        assert (got["estado"], got["ids"]) == (exp["intencao_sem_feature"]["estado"], exp["intencao_sem_feature"]["ids"])
    if "retraducao" in exp:
        got = rep["retraducao"]
        assert got["estado"] == exp["retraducao"]["estado"]
        assert [i["req"] for i in got["itens"]] == exp["retraducao"]["reqs"]
        assert [i["req"] for i in got["itens"] if i["depois"]] == exp["retraducao"]["com_pos_codigo"]
    if "delta" in exp:
        delta = rep["delta"]
        for step, want in exp["delta"].items():
            if step == "mudou":
                assert delta["mudou"] == want
                continue
            got = delta[step]
            assert [got["m1"]["num"], got["m1"]["den"]] == want["m1"]
            assert [got["m2"]["num"], got["m2"]["den"]] == want["m2"]
            assert got["mudanca"] == pytest.approx(want["mudanca"], abs=1e-4)
            if "denominador" in want:
                assert got["denominador"] == want["denominador"]


# ---- golden of plan-000008 (DRM-007): compute_report is pure and reproduces casos.json

@pytest.mark.parametrize("name", sorted(GOLDEN))
def test_golden_case_compute(name):
    entrada, esperado = GOLDEN[name]["entrada"], GOLDEN[name]["esperado"]
    assert dr.compute_report(entrada) == esperado


def test_golden_normal_d1_is_descobertos_over_total():
    rep = dr.compute_report(GOLDEN["normal"]["entrada"])
    d1 = rep["degraus"]["D1"]
    assert d1["D"] == d1["descobertos"] / (d1["cobertos"] + d1["descobertos"])


def test_golden_nada_medido_has_na_and_not_measured_equal_to_n():
    rep = dr.compute_report(GOLDEN["nada-medido"]["entrada"])
    for step in ("D3a", "D3b"):
        assert rep["degraus"][step]["D"] == "n/a"
        assert rep["degraus"][step]["nao_medidos"] == rep["degraus"][step]["n"]


def test_golden_escada_fechada_reading():
    rep = dr.compute_report(GOLDEN["escada-fechada"]["entrada"])
    assert rep["leituras"]["escada_fechou_sem_capturar"] is True


def test_compute_is_deterministic():
    entrada = GOLDEN["normal"]["entrada"]
    a = json.dumps(dr.compute_report(entrada), sort_keys=False)
    b = json.dumps(dr.compute_report(entrada), sort_keys=False)
    assert a == b


def test_compute_does_not_mutate_input():
    entrada = json.loads(json.dumps(GOLDEN["normal"]["entrada"]))
    before = json.dumps(entrada)
    dr.compute_report(entrada)
    assert json.dumps(entrada) == before


# ---- independent recount of every esperado.json (written by hand)

@pytest.mark.parametrize("name", CASES)
def test_esperado_is_internally_consistent(name):
    exp = json.loads((_FIX / name / "esperado.json").read_text(encoding="utf-8"))
    for step, d in exp.get("degraus", {}).items():
        assert d["n"] == d["cobertos"] + d["descobertos"] + d["nao_medidos"], step
        den = d["cobertos"] + d["descobertos"]
        want = round(d["descobertos"] / den, 4) if den else "n/a"
        assert d["D"] == want, step
        if d["nao_medidos"]:
            assert d["razao_nm"], f"{step}: nao medido sem razao"


# ---- trees: load_matrix + compute_report + extras

@pytest.mark.parametrize("name", [c for c in CASES if c != "entrada-corrompida"])
def test_tree_case(name):
    exp, rep = make_report(name)
    check_case(rep, exp)


def test_tree_report_is_byte_for_byte_reproducible():
    _, a = make_report("ok-m2-deriva")
    _, b = make_report("ok-m2-deriva")
    assert json.dumps(a, ensure_ascii=False) == json.dumps(b, ensure_ascii=False)


def test_stale_status_is_consulted_even_when_frontmatter_says_approved():
    calls = []

    def spy(root, slug):
        calls.append(slug)
        return stub_status(root, slug)

    text = (_FIX / "stale" / "features" / SLUG / "intent.md").read_text(encoding="utf-8")
    assert "scenarios: approved" in text
    exp, rep = make_report("stale", status_fn=spy)
    assert calls == [SLUG]
    d1 = rep["degraus"]["D1"]
    assert (d1["razao_nm"], d1["cobertos"], d1["descobertos"]) == (["NM-CENARIOS-STALE"], 0, 0)


def test_skip_and_xfail_are_descobertos_in_d2():
    _, rep = make_report("skip-xfail")
    assert rep["degraus"]["D2"]["descobertos"] == 2


def test_corrupted_gate_is_an_input_error_naming_the_file():
    with pytest.raises(dr.DriftInputError) as err:
        make_report("entrada-corrompida")
    assert "gate.json" in str(err.value)
