"""Tests for drift_report.py -- DRP-001 to DRP-019 over the golden and tree fixtures.

Invocation: test
Lifecycle: active

Rules: .claude/references/general/drift-report.md (DRP-NNN) and drift-metric.md (DRM-NNN).
Golden: fixtures/drift/casos.json (plan-000008; read-only). Trees: fixtures/drift_report/<case>/
(esperado.json written by hand, per case, not generated by the calculator).
"""

from __future__ import annotations

import json
from pathlib import Path

import drift_report as dr
import pytest

_TESTS_DIR = Path(__file__).resolve().parent
_FIX = _TESTS_DIR / "fixtures" / "drift_report"
_GOLDEN = _TESTS_DIR / "fixtures" / "drift" / "casos.json"

GOLDEN = json.loads(_GOLDEN.read_text(encoding="utf-8"))["casos"]
CASES = sorted(p.parent.name for p in _FIX.glob("*/esperado.json"))
SLUG = "contas-da-semana"
STEPS = ("D1", "D2", "D3a", "D3b")


def stub_status(root, slug):
    """Simulated `check_specify.py --status`: the case's status.txt."""
    return (Path(root) / "status.txt").read_text(encoding="utf-8").strip()


def make_report(name, **kw):
    root = _FIX / name
    exp = json.loads((root / "esperado.json").read_text(encoding="utf-8"))
    plan = root / "plan.md"
    return exp, dr.generate(
        root, SLUG, plan=plan if plan.is_file() else None, moment=exp.get("momento", "M2"),
        status_fn=kw.pop("status_fn", stub_status), **kw)


def check_case(rep, exp):
    if exp.get("nao_aplicavel"):
        assert rep.get("nao_aplicavel") is True
        assert rep["razao_nm"] == exp["razao_nm"]
        assert rep.get("motivo") == exp.get("motivo")
        return
    for step, want in exp["degraus"].items():
        got = rep["degraus"][step]
        for field, value in want.items():
            assert got[field] == value, f"{step}.{field}"
    for field, value in exp.get("leituras", {}).items():
        assert rep["leituras"][field] == value, f"leituras.{field}"
    assert rep["ressalvas"] == exp["ressalvas"]
    for field, value in exp.get("auditoria", {}).items():
        assert rep["auditoria"][field] == value, f"auditoria.{field}"
    if "d0" in exp:
        d0 = rep["leituras"]["d0"]
        assert (d0["estado"], d0["frases"], [r["frase"] for r in d0["residuo"]]) == (
            exp["d0"]["estado"], exp["d0"]["frases"], exp["d0"]["residuo"])
    if "intencao_sem_feature" in exp:
        got = rep["leituras"]["intencao_sem_feature"]
        assert (got["estado"], got["ids"]) == (exp["intencao_sem_feature"]["estado"], exp["intencao_sem_feature"]["ids"])
    if "retraducao" in exp:
        got = rep["retraducao"]
        assert got["estado"] == exp["retraducao"]["estado"]
        assert [i["req"] for i in got["itens"]] == exp["retraducao"]["reqs"]
        assert [i["req"] for i in got["itens"] if i["depois"]] == exp["retraducao"]["com_pos_codigo"]
    if "delta" in exp:
        delta = rep["delta"]
        for step, want in exp["delta"].items():
            if step == "mudou":
                assert delta["mudou"] == want
                continue
            got = delta[step]
            assert [got["m1"]["num"], got["m1"]["den"]] == want["m1"]
            assert [got["m2"]["num"], got["m2"]["den"]] == want["m2"]
            assert got["mudanca"] == pytest.approx(want["mudanca"], abs=1e-4)
            if "denominador" in want:
                assert got["denominador"] == want["denominador"]


# ---- golden of plan-000008 (DRM-007): compute_report is pure and reproduces casos.json

@pytest.mark.parametrize("name", sorted(GOLDEN))
def test_golden_case_compute(name):
    entrada, esperado = GOLDEN[name]["entrada"], GOLDEN[name]["esperado"]
    assert dr.compute_report(entrada) == esperado


def test_golden_normal_d1_is_descobertos_over_total():
    rep = dr.compute_report(GOLDEN["normal"]["entrada"])
    d1 = rep["degraus"]["D1"]
    assert d1["D"] == d1["descobertos"] / (d1["cobertos"] + d1["descobertos"])


def test_golden_nada_medido_has_na_and_not_measured_equal_to_n():
    rep = dr.compute_report(GOLDEN["nada-medido"]["entrada"])
    for step in ("D3a", "D3b"):
        assert rep["degraus"][step]["D"] == "n/a"
        assert rep["degraus"][step]["nao_medidos"] == rep["degraus"][step]["n"]


def test_golden_escada_fechada_reading():
    rep = dr.compute_report(GOLDEN["escada-fechada"]["entrada"])
    assert rep["leituras"]["escada_fechou_sem_capturar"] is True


def test_compute_is_deterministic():
    entrada = GOLDEN["normal"]["entrada"]
    a = json.dumps(dr.compute_report(entrada), sort_keys=False)
    b = json.dumps(dr.compute_report(entrada), sort_keys=False)
    assert a == b


def test_compute_does_not_mutate_input():
    entrada = json.loads(json.dumps(GOLDEN["normal"]["entrada"]))
    before = json.dumps(entrada)
    dr.compute_report(entrada)
    assert json.dumps(entrada) == before


# ---- independent recount of every esperado.json (written by hand)

@pytest.mark.parametrize("name", CASES)
def test_esperado_is_internally_consistent(name):
    exp = json.loads((_FIX / name / "esperado.json").read_text(encoding="utf-8"))
    for step, d in exp.get("degraus", {}).items():
        assert d["n"] == d["cobertos"] + d["descobertos"] + d["nao_medidos"], step
        den = d["cobertos"] + d["descobertos"]
        want = round(d["descobertos"] / den, 4) if den else "n/a"
        assert d["D"] == want, step
        if d["nao_medidos"]:
            assert d["razao_nm"], f"{step}: nao medido sem razao"


# ---- trees: load_matrix + compute_report + extras

@pytest.mark.parametrize("name", [c for c in CASES if c != "entrada-corrompida"])
def test_tree_case(name):
    exp, rep = make_report(name)
    check_case(rep, exp)


def test_tree_report_is_byte_for_byte_reproducible():
    _, a = make_report("ok-m2-deriva")
    _, b = make_report("ok-m2-deriva")
    assert json.dumps(a, ensure_ascii=False) == json.dumps(b, ensure_ascii=False)


def test_stale_status_is_consulted_even_when_frontmatter_says_approved():
    calls = []

    def spy(root, slug):
        calls.append(slug)
        return stub_status(root, slug)

    text = (_FIX / "stale" / "features" / SLUG / "intent.md").read_text(encoding="utf-8")
    assert "scenarios: approved" in text
    _, rep = make_report("stale", status_fn=spy)
    assert calls == [SLUG]
    d1 = rep["degraus"]["D1"]
    assert (d1["razao_nm"], d1["cobertos"], d1["descobertos"]) == (["NM-CENARIOS-STALE"], 0, 0)


def test_skip_and_xfail_are_descobertos_in_d2():
    _, rep = make_report("skip-xfail")
    assert rep["degraus"]["D2"]["descobertos"] == 2


def test_corrupted_gate_is_an_input_error_naming_the_file():
    with pytest.raises(dr.DriftInputError) as err:
        make_report("entrada-corrompida")
    assert "gate.json" in str(err.value)


# ---- Step 4: calculator cases built from small matrices

def small(**over):
    base = {
        "feature": "t", "momento": "M1", "intent": {"status": "approved"}, "scenarios_status": "approved",
        "runner": {"adaptador": True, "relatorio": True}, "gate": {"full": "PASS", "baseline_moved": False},
        "reqs": ["REQ-t-001"], "scenarios": [], "touched": {"total": 4, "uncovered": 1}, "oraculo": None, "auditoria": [],
    }
    base.update(over)
    return base


def scen(i, test_result="passed", red=True, tags=("REQ-t-001",), **kw):
    return dict({"id": i, "tags": list(tags), "test_result": test_result, "red_reason_ok": red}, **kw)


def test_three_covered_one_uncovered_two_not_measured_gives_a_quarter():
    reqs = [f"REQ-t-00{n}" for n in range(1, 7)]
    scenarios = [scen("S1", tags=(reqs[0],)), scen("S2", tags=(reqs[1],)), scen("S3", tags=(reqs[2],)),
                 scen("S4", "absent", None, tags=(reqs[3],))]
    rep = dr.compute_report(small(reqs=reqs, scenarios=scenarios, scenarios_status="stale"))
    d1 = rep["degraus"]["D1"]
    assert (d1["nao_medidos"], d1["razao_nm"], d1["D"]) == (6, ["NM-CENARIOS-STALE"], "n/a")
    d2 = rep["degraus"]["D2"]
    assert (d2["cobertos"], d2["descobertos"], d2["D"]) == (3, 1, 0.25)


def test_zero_denominator_is_na_not_zero():
    rep = dr.compute_report(small(reqs=[], scenarios=[], touched={"total": 0, "uncovered": 0}))
    assert all(rep["degraus"][s]["D"] == "n/a" for s in dr.STEPS)


def test_baseline_accepted_makes_d3a_descoberto_with_caveat():
    rep = dr.compute_report(small(scenarios=[scen("S1")], gate={"full": "PASS", "baseline_moved": True}))
    assert rep["degraus"]["D3a"]["descobertos"] == 1
    assert "baseline aceito" in rep["ressalvas"]


def test_d3a_population_excludes_scenarios_without_test():
    rep = dr.compute_report(small(scenarios=[scen("S1"), scen("S2", "absent", None)]))
    assert rep["degraus"]["D3a"]["n"] == 1


def test_error_and_undefined_are_covered_in_d2_and_uncovered_in_d3a():
    rep = dr.compute_report(small(scenarios=[scen("S1", "error"), scen("S2", "undefined")]))
    assert (rep["degraus"]["D2"]["cobertos"], rep["degraus"]["D3a"]["descobertos"]) == (2, 2)


def test_not_measured_never_enters_the_denominator():
    rep = dr.compute_report(small(scenarios=[scen("S1"), scen("S2", red=None)]))
    d3a = rep["degraus"]["D3a"]
    assert (d3a["cobertos"], d3a["nao_medidos"], d3a["D"]) == (1, 1, 0.0)


def test_calculator_module_layer_has_no_io_imports_in_compute():
    src = Path(dr.__file__).read_text(encoding="utf-8")
    start = src.index("def analyze(")
    end = src.index("def compute_report(")
    block = src[start:end]
    for word in ("subprocess", "socket", "anthropic", "open(", "os.environ"):
        assert word not in block


# ---- Step 5: loader behaviors

def test_audit_never_changes_any_d():
    _, with_audit = make_report("auditoria")
    _, without = make_report("ok-m1")
    assert with_audit["degraus"] == without["degraus"]


def test_missing_check_specify_adds_caveat_and_never_silent_approved(tmp_path):
    root = tmp_path / "p"
    (root).mkdir()
    for p in (_FIX / "ok-m1").rglob("*"):
        if p.is_file() and p.name not in ("esperado.json", "status.txt"):
            dest = root / p.relative_to(_FIX / "ok-m1")
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(p.read_bytes())
    scripts = tmp_path / "scripts"
    scripts.mkdir()
    real = Path(dr.__file__).resolve().parent
    for name in ("check_features.py", "check_intent.py"):
        (scripts / name).write_bytes((real / name).read_bytes())
    # check_specify.py is not in the copy: the approval is not verified
    rep = dr.generate(root, SLUG, moment="M1", scripts_dir=scripts)
    assert "aprovação não verificada" in rep["ressalvas"]


def test_missing_check_features_is_an_input_error(tmp_path):
    (tmp_path / "features" / SLUG).mkdir(parents=True)
    with pytest.raises(dr.DriftInputError):
        dr.load_matrix(tmp_path, SLUG, scripts_dir=tmp_path / "vazio", status_fn=lambda r, s: "approved")


def test_project_without_features_is_not_applicable_and_touches_no_file(tmp_path):
    matrix = dr.load_matrix(tmp_path, SLUG)
    assert matrix["nao_aplicavel"] and matrix["motivo"] == "sem-features"
    assert list(tmp_path.iterdir()) == []


def test_v1_plan_is_not_applicable_and_reads_nothing_else(tmp_path):
    plan = tmp_path / "plan.md"
    plan.write_text((_FIX / "plano-v1" / "plan.md").read_text(encoding="utf-8"), encoding="utf-8")
    called = []
    matrix = dr.load_matrix(tmp_path, SLUG, plan=plan, run_fn=lambda a: called.append(a) or (0, "", ""))
    assert matrix["motivo"] == "plano-v1" and called == []


def test_runner_orphan_test_stays_outside_every_d(tmp_path):
    root = tmp_path / "p"
    src = _FIX / "ok-m1"
    for p in src.rglob("*"):
        if p.is_file():
            dest = root / p.relative_to(src)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(p.read_bytes())
    path = root / "features" / SLUG / "runner" / "cucumber.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    ghost = json.loads(json.dumps(data[0]["elements"][0]))
    ghost["name"] = "Cenário que não existe mais"
    data[0]["elements"].append(ghost)
    path.write_text(json.dumps(data), encoding="utf-8")
    rep = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    assert rep["leituras"]["testes_orfaos"] == 1
    assert rep["degraus"]["D2"]["n"] == 4


def test_invalid_audit_value_is_an_error_naming_the_req(tmp_path):
    path = tmp_path / "audit.json"
    path.write_text(json.dumps({"itens": [{"req": "REQ-x-001", "adequado": "talvez"}]}), encoding="utf-8")
    with pytest.raises(dr.DriftInputError) as err:
        dr.read_audit(path)
    assert "REQ-x-001" in str(err.value)


def test_plan_step_mapping_is_not_part_of_the_vector():
    # a v2 plan is accepted and does not change any D
    root = _FIX / "ok-m1"
    with_plan = dr.generate(root, SLUG, plan=root / "plan.md", moment="M1", status_fn=stub_status)
    without = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    assert with_plan["degraus"] == without["degraus"]


def test_loader_has_no_shell_true():
    assert "shell=True" not in Path(dr.__file__).read_text(encoding="utf-8")


def test_integration_with_the_three_real_scripts():
    """check_features, check_specify and check_plan_scenarios run for real over a committed fixture."""
    base = _TESTS_DIR / "fixtures" / "plan_scenarios"
    root = base / "_raizes" / "aprovada"
    matrix = dr.load_matrix(root, SLUG, plan=base / "v2-completo" / "plan.md", moment="M1")
    assert matrix["scenarios_status"] == "approved"
    assert len(matrix["reqs"]) == 3 and len(matrix["scenarios"]) == 4
    assert len(matrix["extras"]["step_dono"]) == 4
    rep = dr.build_report(matrix)
    assert rep["degraus"]["D1"]["cobertos"] == 3
    assert rep["degraus"]["D2"]["razao_nm"] == ["NM-SEM-RUNNER"]
    assert rep["degraus"]["D3a"]["razao_nm"] == ["NM-SEM-RUNNER", "NM-SEM-GATE"]
