"""Tests for drift_report.py -- DRP-001 to DRP-019 over the golden and tree fixtures.

Invocation: test
Lifecycle: active

Rules: .claude/references/general/drift-report.md (DRP-NNN) and drift-metric.md (DRM-NNN).
Golden: fixtures/drift/casos.json (plan-000008; read-only). Trees: fixtures/drift_report/<case>/
(esperado.json written by hand, per case, not generated by the calculator).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import drift_report as dr
import pytest

_TESTS_DIR = Path(__file__).resolve().parent
_FIX = _TESTS_DIR / "fixtures" / "drift_report"
_GOLDEN = _TESTS_DIR / "fixtures" / "drift" / "casos.json"

GOLDEN = json.loads(_GOLDEN.read_text(encoding="utf-8"))["casos"]
CASES = sorted(p.parent.name for p in _FIX.glob("*/esperado.json"))
SLUG = "contas-da-semana"
STEPS = ("D1", "D2", "D3a", "D3b")


def stub_status(root, slug):
    """Simulated `check_specify.py --status`: the case's status.txt."""
    return (Path(root) / "status.txt").read_text(encoding="utf-8").strip()


def make_report(name, **kw):
    root = _FIX / name
    exp = json.loads((root / "esperado.json").read_text(encoding="utf-8"))
    plan = root / "plan.md"
    return exp, dr.generate(
        root, SLUG, plan=plan if plan.is_file() else None, moment=exp.get("momento", "M2"),
        compare_m1=True, status_fn=kw.pop("status_fn", stub_status), **kw)


def check_case(rep, exp):
    if exp.get("nao_aplicavel"):
        assert rep.get("nao_aplicavel") is True
        assert rep["razao_nm"] == exp["razao_nm"]
        assert rep.get("motivo") == exp.get("motivo")
        return
    for step, want in exp["degraus"].items():
        got = rep["degraus"][step]
        for field, value in want.items():
            assert got[field] == value, f"{step}.{field}"
    for field, value in exp.get("leituras", {}).items():
        assert rep["leituras"][field] == value, f"leituras.{field}"
    assert rep["ressalvas"] == exp["ressalvas"]
    for field, value in exp.get("auditoria", {}).items():
        assert rep["auditoria"][field] == value, f"auditoria.{field}"
    if "d0" in exp:
        d0 = rep["leituras"]["d0"]
        assert (d0["estado"], d0["frases"], [r["frase"] for r in d0["residuo"]]) == (
            exp["d0"]["estado"], exp["d0"]["frases"], exp["d0"]["residuo"])
    if "intencao_sem_feature" in exp:
        got = rep["leituras"]["intencao_sem_feature"]
        assert (got["estado"], got["ids"]) == (exp["intencao_sem_feature"]["estado"], exp["intencao_sem_feature"]["ids"])
    if "retraducao" in exp:
        got = rep["retraducao"]
        assert got["estado"] == exp["retraducao"]["estado"]
        assert [i["req"] for i in got["itens"]] == exp["retraducao"]["reqs"]
        assert [i["req"] for i in got["itens"] if i["depois"]] == exp["retraducao"]["com_pos_codigo"]
    if "delta" in exp:
        delta = rep["delta"]
        for step, want in exp["delta"].items():
            if step == "mudou":
                assert delta["mudou"] == want
                continue
            got = delta[step]
            assert [got["m1"]["num"], got["m1"]["den"]] == want["m1"]
            assert [got["m2"]["num"], got["m2"]["den"]] == want["m2"]
            assert got["mudanca"] == pytest.approx(want["mudanca"], abs=1e-4)
            if "denominador" in want:
                assert got["denominador"] == want["denominador"]


# ---- golden of plan-000008 (DRM-007): compute_report is pure and reproduces casos.json

@pytest.mark.parametrize("name", sorted(GOLDEN))
def test_golden_case_compute(name):
    entrada, esperado = GOLDEN[name]["entrada"], GOLDEN[name]["esperado"]
    assert dr.compute_report(entrada) == esperado


def test_golden_normal_d1_is_descobertos_over_total():
    rep = dr.compute_report(GOLDEN["normal"]["entrada"])
    d1 = rep["degraus"]["D1"]
    assert d1["D"] == d1["descobertos"] / (d1["cobertos"] + d1["descobertos"])


def test_golden_nada_medido_has_na_and_not_measured_equal_to_n():
    rep = dr.compute_report(GOLDEN["nada-medido"]["entrada"])
    for step in ("D3a", "D3b"):
        assert rep["degraus"][step]["D"] == "n/a"
        assert rep["degraus"][step]["nao_medidos"] == rep["degraus"][step]["n"]


def test_golden_escada_fechada_reading():
    rep = dr.compute_report(GOLDEN["escada-fechada"]["entrada"])
    assert rep["leituras"]["escada_fechou_sem_capturar"] is True


def test_compute_is_deterministic():
    entrada = GOLDEN["normal"]["entrada"]
    a = json.dumps(dr.compute_report(entrada), sort_keys=False)
    b = json.dumps(dr.compute_report(entrada), sort_keys=False)
    assert a == b


def test_compute_does_not_mutate_input():
    entrada = json.loads(json.dumps(GOLDEN["normal"]["entrada"]))
    before = json.dumps(entrada)
    dr.compute_report(entrada)
    assert json.dumps(entrada) == before


# ---- independent recount of every esperado.json (written by hand)

@pytest.mark.parametrize("name", CASES)
def test_esperado_is_internally_consistent(name):
    exp = json.loads((_FIX / name / "esperado.json").read_text(encoding="utf-8"))
    for step, d in exp.get("degraus", {}).items():
        assert d["n"] == d["cobertos"] + d["descobertos"] + d["nao_medidos"], step
        den = d["cobertos"] + d["descobertos"]
        want = round(d["descobertos"] / den, 4) if den else "n/a"
        assert d["D"] == want, step
        if d["nao_medidos"]:
            assert d["razao_nm"], f"{step}: nao medido sem razao"


# ---- trees: load_matrix + compute_report + extras

@pytest.mark.parametrize("name", [c for c in CASES if c != "entrada-corrompida"])
def test_tree_case(name):
    exp, rep = make_report(name)
    check_case(rep, exp)


def test_tree_report_is_byte_for_byte_reproducible():
    _, a = make_report("ok-m2-deriva")
    _, b = make_report("ok-m2-deriva")
    assert json.dumps(a, ensure_ascii=False) == json.dumps(b, ensure_ascii=False)


def test_stale_status_is_consulted_even_when_frontmatter_says_approved():
    calls = []

    def spy(root, slug):
        calls.append(slug)
        return stub_status(root, slug)

    text = (_FIX / "stale" / "features" / SLUG / "intent.md").read_text(encoding="utf-8")
    assert "scenarios: approved" in text
    _, rep = make_report("stale", status_fn=spy)
    assert calls == [SLUG]
    d1 = rep["degraus"]["D1"]
    assert (d1["razao_nm"], d1["cobertos"], d1["descobertos"]) == (["NM-CENARIOS-STALE"], 0, 0)


def test_skip_and_xfail_are_descobertos_in_d2():
    _, rep = make_report("skip-xfail")
    assert rep["degraus"]["D2"]["descobertos"] == 2


def test_corrupted_gate_is_an_input_error_naming_the_file():
    with pytest.raises(dr.DriftInputError) as err:
        make_report("entrada-corrompida")
    assert "gate.json" in str(err.value)


# ---- Step 4: calculator cases built from small matrices

def small(**over):
    base = {
        "feature": "t", "momento": "M1", "intent": {"status": "approved"}, "scenarios_status": "approved",
        "runner": {"adaptador": True, "relatorio": True}, "gate": {"full": "PASS", "baseline_moved": False},
        "reqs": ["REQ-t-001"], "scenarios": [], "touched": {"total": 4, "uncovered": 1}, "oraculo": None, "auditoria": [],
    }
    base.update(over)
    return base


def scen(i, test_result="passed", red=True, tags=("REQ-t-001",), **kw):
    return dict({"id": i, "tags": list(tags), "test_result": test_result, "red_reason_ok": red}, **kw)


def test_three_covered_one_uncovered_two_not_measured_gives_a_quarter():
    reqs = [f"REQ-t-00{n}" for n in range(1, 7)]
    scenarios = [scen("S1", tags=(reqs[0],)), scen("S2", tags=(reqs[1],)), scen("S3", tags=(reqs[2],)),
                 scen("S4", "absent", None, tags=(reqs[3],))]
    rep = dr.compute_report(small(reqs=reqs, scenarios=scenarios, scenarios_status="stale"))
    d1 = rep["degraus"]["D1"]
    assert (d1["nao_medidos"], d1["razao_nm"], d1["D"]) == (6, ["NM-CENARIOS-STALE"], "n/a")
    d2 = rep["degraus"]["D2"]
    assert (d2["cobertos"], d2["descobertos"], d2["D"]) == (3, 1, 0.25)


def test_zero_denominator_is_na_not_zero():
    rep = dr.compute_report(small(reqs=[], scenarios=[], touched={"total": 0, "uncovered": 0}))
    assert all(rep["degraus"][s]["D"] == "n/a" for s in dr.STEPS)


def test_baseline_accepted_makes_d3a_descoberto_with_caveat():
    rep = dr.compute_report(small(scenarios=[scen("S1")], gate={"full": "PASS", "baseline_moved": True}))
    assert rep["degraus"]["D3a"]["descobertos"] == 1
    assert "baseline aceito" in rep["ressalvas"]


def test_d3a_population_excludes_scenarios_without_test():
    rep = dr.compute_report(small(scenarios=[scen("S1"), scen("S2", "absent", None)]))
    assert rep["degraus"]["D3a"]["n"] == 1


def test_error_and_undefined_are_covered_in_d2_and_uncovered_in_d3a():
    rep = dr.compute_report(small(scenarios=[scen("S1", "error"), scen("S2", "undefined")]))
    assert (rep["degraus"]["D2"]["cobertos"], rep["degraus"]["D3a"]["descobertos"]) == (2, 2)


def test_not_measured_never_enters_the_denominator():
    rep = dr.compute_report(small(scenarios=[scen("S1"), scen("S2", red=None)]))
    d3a = rep["degraus"]["D3a"]
    assert (d3a["cobertos"], d3a["nao_medidos"], d3a["D"]) == (1, 1, 0.0)


def test_calculator_module_layer_has_no_io_imports_in_compute():
    src = Path(dr.__file__).read_text(encoding="utf-8")
    start = src.index("def analyze(")
    end = src.index("def compute_report(")
    block = src[start:end]
    for word in ("subprocess", "socket", "anthropic", "open(", "os.environ"):
        assert word not in block


# ---- Step 5: loader behaviors

def test_audit_never_changes_any_d():
    _, with_audit = make_report("auditoria")
    _, without = make_report("ok-m1")
    assert with_audit["degraus"] == without["degraus"]


def test_missing_check_specify_adds_caveat_and_never_silent_approved(tmp_path):
    root = tmp_path / "p"
    (root).mkdir()
    for p in (_FIX / "ok-m1").rglob("*"):
        if p.is_file() and p.name not in ("esperado.json", "status.txt"):
            dest = root / p.relative_to(_FIX / "ok-m1")
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(p.read_bytes())
    scripts = tmp_path / "scripts"
    scripts.mkdir()
    real = Path(dr.__file__).resolve().parent
    for name in ("check_features.py", "check_intent.py"):
        (scripts / name).write_bytes((real / name).read_bytes())
    # check_specify.py is not in the copy: the approval is not verified
    rep = dr.generate(root, SLUG, moment="M1", scripts_dir=scripts)
    assert "aprovação não verificada" in rep["ressalvas"]


def test_missing_check_features_is_an_input_error(tmp_path):
    (tmp_path / "features" / SLUG).mkdir(parents=True)
    with pytest.raises(dr.DriftInputError):
        dr.load_matrix(tmp_path, SLUG, scripts_dir=tmp_path / "vazio", status_fn=lambda r, s: "approved")


def test_project_without_features_is_not_applicable_and_touches_no_file(tmp_path):
    matrix = dr.load_matrix(tmp_path, SLUG)
    assert matrix["nao_aplicavel"] and matrix["motivo"] == "sem-features"
    assert list(tmp_path.iterdir()) == []


def test_v1_plan_is_not_applicable_and_reads_nothing_else(tmp_path):
    plan = tmp_path / "plan.md"
    plan.write_text((_FIX / "plano-v1" / "plan.md").read_text(encoding="utf-8"), encoding="utf-8")
    called = []
    matrix = dr.load_matrix(tmp_path, SLUG, plan=plan, run_fn=lambda a: called.append(a) or (0, "", ""))
    assert matrix["motivo"] == "plano-v1" and called == []


def test_runner_orphan_test_stays_outside_every_d(tmp_path):
    root = tmp_path / "p"
    src = _FIX / "ok-m1"
    for p in src.rglob("*"):
        if p.is_file():
            dest = root / p.relative_to(src)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(p.read_bytes())
    path = root / "features" / SLUG / "runner" / "cucumber.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    ghost = json.loads(json.dumps(data[0]["elements"][0]))
    ghost["name"] = "Cenário que não existe mais"
    data[0]["elements"].append(ghost)
    path.write_text(json.dumps(data), encoding="utf-8")
    rep = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    assert rep["leituras"]["testes_orfaos"] == 1
    assert rep["degraus"]["D2"]["n"] == 4


def test_invalid_audit_value_is_an_error_naming_the_req(tmp_path):
    path = tmp_path / "audit.json"
    path.write_text(json.dumps({"itens": [{"req": "REQ-x-001", "adequado": "talvez"}]}), encoding="utf-8")
    with pytest.raises(dr.DriftInputError) as err:
        dr.read_audit(path)
    assert "REQ-x-001" in str(err.value)


def test_plan_step_mapping_is_not_part_of_the_vector():
    # a v2 plan is accepted and does not change any D
    root = _FIX / "ok-m1"
    with_plan = dr.generate(root, SLUG, plan=root / "plan.md", moment="M1", status_fn=stub_status)
    without = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    assert with_plan["degraus"] == without["degraus"]


def test_loader_has_no_shell_true():
    assert "shell=True" not in Path(dr.__file__).read_text(encoding="utf-8")


def test_integration_with_the_three_real_scripts():
    """check_features, check_specify and check_plan_scenarios run for real over a committed fixture."""
    base = _TESTS_DIR / "fixtures" / "plan_scenarios"
    root = base / "_raizes" / "aprovada"
    matrix = dr.load_matrix(root, SLUG, plan=base / "v2-completo" / "plan.md", moment="M1")
    assert matrix["scenarios_status"] == "approved"
    assert len(matrix["reqs"]) == 3 and len(matrix["scenarios"]) == 4
    assert len(matrix["extras"]["step_dono"]) == 4
    rep = dr.build_report(matrix)
    assert rep["degraus"]["D1"]["cobertos"] == 3
    assert rep["degraus"]["D2"]["razao_nm"] == ["NM-SEM-RUNNER"]
    assert rep["degraus"]["D3a"]["razao_nm"] == ["NM-SEM-RUNNER", "NM-SEM-GATE"]


# ---- Step 6: snapshots, delta, audit sample, CLI

def copy_tree(src, dst):
    for p in Path(src).rglob("*"):
        if p.is_file():
            out = Path(dst) / p.relative_to(src)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(p.read_bytes())
    return Path(dst)


def test_freeze_refuses_to_overwrite_m1_and_leaves_the_file_intact(tmp_path):
    root = copy_tree(_FIX / "ok-m1", tmp_path / "p")
    report = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    path = dr.freeze(report, root, SLUG, "M1", "2026-10-06T18:00:00Z")
    before = path.read_bytes()
    with pytest.raises(FileExistsError):
        dr.freeze(report, root, SLUG, "M1", "2026-10-07T18:00:00Z")
    assert path.read_bytes() == before


def test_freeze_writes_only_under_drift(tmp_path):
    root = copy_tree(_FIX / "ok-m1", tmp_path / "p")
    before = {p.relative_to(root) for p in root.rglob("*") if p.is_file()}
    report = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    dr.freeze(report, root, SLUG, "M1", "2026-10-06T18:00:00Z")
    after = {p.relative_to(root) for p in root.rglob("*") if p.is_file()}
    assert [str(p) for p in after - before] == [f"features/{SLUG}/drift/M1.json"]


def test_compare_without_m1_says_so_and_has_no_numeric_delta():
    rep = dr.generate(_FIX / "ok-m1", SLUG, moment="M2", compare_m1=True, status_fn=stub_status)
    assert rep["delta"] == {"estado": "nao_medido", "razao_nm": ["NM-SEM-M1"]}


def test_delta_notes_the_changed_denominator_and_keeps_both_sides():
    _, rep = make_report("denominador-muda")
    d1 = rep["delta"]["D1"]
    assert d1["denominador"] == "o denominador mudou de 3 para 4"
    assert (d1["m1"]["den"], d1["m2"]["den"]) == (3, 4)


def test_delta_change_is_none_when_a_side_is_not_a_number():
    m1 = {"report": {"degraus": {"D1": {"cobertos": 0, "descobertos": 0, "D": "n/a"}}}, "entradas": {}}
    m2 = {"degraus": {"D1": {"cobertos": 3, "descobertos": 1, "D": 0.25}}, "entradas": {}}
    assert dr.compare(m1, m2)["D1"]["mudanca"] is None


def test_audit_sample_is_deterministic_and_is_thirty_percent_rounded_up():
    reqs = [f"REQ-x-{n:03d}" for n in range(1, 11)]
    a = dr.audit_sample(reqs, "x")
    assert len(a) == 3 and a == dr.audit_sample(list(reversed(reqs)), "x")
    assert dr.audit_sample(reqs[:1], "x") == reqs[:1]


def test_audit_sample_changes_no_d():
    _, rep = make_report("ok-m1")
    before = json.dumps(rep["degraus"])
    dr.audit_sample(["REQ-x-001"], "x")
    assert json.dumps(rep["degraus"]) == before


def run_cli(args, capsys):
    code = dr.main(args)
    out = capsys.readouterr()
    return code, out.out, out.err


def test_cli_json_twice_is_identical(capsys):
    root = str(_FIX / "ok-m2-deriva")
    argv = [root, "--feature", SLUG, "--moment", "M2", "--compare", "--json"]
    # status comes from the real check_specify: use a project it can read
    a = run_cli(argv, capsys)
    b = run_cli(argv, capsys)
    assert a == b and a[0] == 0


def test_cli_freeze_needs_at(capsys):
    code, _, err = run_cli([str(_FIX / "ok-m1"), "--feature", SLUG, "--freeze", "--moment", "M1"], capsys)
    assert code == 2 and "--at" in err


def test_cli_without_feature_flag_reports_each_folder_in_alphabetical_order(tmp_path, capsys):
    base = _TESTS_DIR / "fixtures" / "plan_scenarios" / "_raizes" / "aprovada"
    root = copy_tree(base, tmp_path / "p")
    copy_tree(base / "features" / SLUG, root / "features" / "outra-feature")
    code, out, _ = run_cli([str(root), "--moment", "M1", "--json"], capsys)
    names = [r["feature"] for r in json.loads(out)["relatorios"]]
    assert code == 0 and names == sorted(names) and len(names) == 2


def test_cli_invalid_gate_exits_2_naming_the_file(capsys):
    code, _, err = run_cli([str(_FIX / "entrada-corrompida"), "--feature", SLUG, "--json"], capsys)
    assert code == 2 and "gate.json" in err and "Traceback" not in err


def test_cli_project_without_features_is_one_line_and_exit_0(tmp_path, capsys):
    code, out, _ = run_cli([str(tmp_path)], capsys)
    assert code == 0 and out.strip() == "Não aplicável: este projeto não tem features."


def test_cli_audit_sample_lists_reqs_and_exits_0(capsys):
    base = _TESTS_DIR / "fixtures" / "plan_scenarios" / "_raizes" / "aprovada"
    code, out, _ = run_cli([str(base), "--feature", SLUG, "--audit-sample"], capsys)
    assert code == 0 and len(out.split()) == 1


# ---- Step 7: renderers (voice, non-prescriptive, citizen register, HTML)

RENDER_CASES = [c for c in CASES if c not in ("entrada-corrompida",)]


def reports_for_render():
    for name in RENDER_CASES:
        _, rep = make_report(name)
        yield name, rep


@pytest.mark.parametrize("name", RENDER_CASES)
def test_no_forbidden_phrase_in_any_register(name):
    _, rep = make_report(name)
    for text in (dr.render_markdown(rep), dr.render_citizen(rep), dr.render_html(rep), dr.render_html(rep, citizen=True)):
        low = text.lower()
        assert not [p for p in dr.FORBIDDEN_PHRASES if p in low]


@pytest.mark.parametrize("name", RENDER_CASES)
def test_voice_limits_hold_for_both_registers(name):
    _, rep = make_report(name)
    assert dr.check_voice(dr.render_markdown(rep)) == []
    assert dr.check_voice(dr.render_citizen(rep)) == []


@pytest.mark.parametrize("name", RENDER_CASES)
def test_citizen_register_has_no_technical_number_or_tool_word(name):
    _, rep = make_report(name)
    text = dr.render_citizen(rep)
    plain = re.sub(r'"[^"]*"', "", text)  # the citizen's own words may carry domain numbers
    assert not re.search(r"\d", plain), plain
    assert "%" not in text
    for word in ("PASS", "gate", "CRAP", "D1", "D2", "D3a", "D3b", "baseline", "NM-"):
        assert word not in text


def test_not_measured_reason_sits_on_the_same_table_row():
    _, rep = make_report("sem-gate")
    row = next(ln for ln in dr.render_markdown(rep).splitlines() if ln.startswith("| D3a"))
    assert "NM-SEM-GATE" in row


def test_all_na_has_no_highlight_and_says_nothing_to_measure():
    rep = dr.compute_report(small(reqs=[], scenarios=[], touched=None))
    full = dr.build_report({**small(reqs=[], scenarios=[], touched=None), "extras": {}})
    text = dr.render_markdown(full)
    assert "Nenhum degrau tinha itens para medir." in text and "O maior D" not in text
    assert rep["degraus"]["D1"]["D"] == "n/a"


def test_tie_is_said_as_a_tie():
    _, rep = make_report("ok-m2-deriva")
    assert dr.highlight(rep) == "Empate entre D3a e D3b."


def test_highlight_names_the_step_and_the_count():
    _, rep = make_report("ok-m1")
    assert dr.highlight(rep).startswith("O maior D está em D3b: 2 de 20 linhas")


def test_audit_sentence_is_present_when_there_is_an_audit():
    _, rep = make_report("auditoria")
    assert "A auditoria não entra no D." in dr.render_markdown(rep)


@pytest.mark.parametrize("name,line", [("sem-features", "Não aplicável: este projeto não tem features."),
                                       ("plano-v1", "Não aplicável: este plano é do formato antigo."),
                                       ("specify-pulado", "Não aplicável: esta tarefa não teve cenários.")])
def test_not_applicable_is_exactly_one_line_in_every_register(name, line):
    _, rep = make_report(name)
    assert dr.render_markdown(rep) == line + "\n" and dr.render_citizen(rep) == line + "\n"


def test_citizen_lists_only_absences_and_what_changed():
    _, rep = make_report("ok-m2-deriva")
    text = dr.render_citizen(rep)
    assert "Desfazer uma conta marcada como paga por engano" in text
    assert "Depois da entrega, mais cenários deixaram de passar." in text
    assert "têm teste que rodou" not in text  # a count that only confirms does not enter


def test_citizen_counts_are_in_words():
    assert [dr.words(n) for n in (0, 1, 2, 12, 21, 40, 99, 100)] == [
        "zero", "um", "dois", "doze", "vinte e um", "quarenta", "noventa e nove", "muitos"]


def test_md_of_the_deriva_case_fits_one_screen_apart_from_the_sources_line():
    _, rep = make_report("ok-m2-deriva")
    lines = [ln for ln in dr.render_markdown(rep, at="2026-10-07T10:00:00Z").splitlines() if not ln.startswith("Medido em")]
    assert len(lines) <= 45, len(lines)


def test_markdown_is_deterministic():
    _, a = make_report("ok-m2-deriva")
    _, b = make_report("ok-m2-deriva")
    assert dr.render_markdown(a) == dr.render_markdown(b)


def test_html_is_self_contained_and_escaped():
    _, rep = make_report("ok-m1")
    rep["itens"]["cenarios_descobertos"]["D2"] = [{"chave": "k", "nome": "<script>alert(1)</script>"}]
    text = dr.render_html(rep)
    assert "<script" not in text and "&lt;script&gt;" in text
    for ext in ("http://", "https://", "src=", "<link", "@import", "url("):
        assert ext not in text
    assert "2 de 20" in text  # the number is in the text, not only in the bar


def test_html_option_writes_the_file_and_exits_0(tmp_path, capsys):
    root = copy_tree(_FIX / "ok-m1", tmp_path / "p")
    code = dr.main([str(root), "--feature", SLUG, "--moment", "M1", "--html", "--out", str(tmp_path / "out")])
    capsys.readouterr()
    assert code == 0 and (tmp_path / "out" / f"{SLUG}-M1.html").is_file()


def test_as_coded_table_is_regenerated_from_the_matrix():
    rep = dr.generate(_FIX / "ok-m2-deriva", SLUG, moment="M2", status_fn=stub_status, as_coded=True)
    text = dr.render_markdown(rep)
    assert "### Como ficou (regenerado da matriz)" in text
    assert "| REQ-contas-da-semana-002 | Desfazer uma conta marcada como paga por engano | falhou | não |" in text


def test_retranslation_side_by_side_has_three_columns_for_each_requirement():
    _, rep = make_report("retraducao-pos-codigo")
    text = dr.render_markdown(rep)
    assert "| Requisito | Você pediu | Eu entendi antes do código | Eu entendi depois do código |" in text
    assert dr.render_citizen(rep).count("Eu entendi depois do código:") == 2


def test_missing_post_code_retranslation_says_so_and_invents_nothing():
    _, rep = make_report("ok-m1")
    assert rep["retraducao"]["estado"] == "nao_medido"
    assert dr.NM_SENTENCE["NM-SEM-RETRADUCAO-POS-CODIGO"] in dr.render_markdown(rep)


def test_every_nm_sentence_fits_the_voice_limit():
    for code, sentence in dr.NM_SENTENCE.items():
        assert len(sentence.split()) <= dr.MAX_SENTENCE_WORDS, code
    assert set(dr.NM_SENTENCE) == set(dr.NM_CATALOG)


# ---- Step 8: the skill text is minimal and conditional

_SKILLS = _TESTS_DIR.parents[1]


def skill_text(*parts):
    return (_SKILLS.joinpath(*parts)).read_text(encoding="utf-8")


def test_reflect_section_is_conditioned_on_feature_and_omitted_otherwise():
    text = skill_text("reflect", "SKILL.md")
    assert "Divergência por degrau" in text
    assert "`Feature: <slug>`" in text and "omit this whole section when Step B1 did not run" in text
    assert "drift_report.py --feature <slug> --plan <plan file> --moment M2 --compare --md" in text
    for keep in ("--deep", "--telemetry", "# Reflection <id> | <current datetime> | <short title>"):
        assert keep in text


def test_explain_drift_gets_the_ladder_scope_and_a_conditional_step():
    assert "ladder [<slug>]" in skill_text("explain", "SKILL.md")
    text = skill_text("_internal", "explain", "drift", "SKILL.md")
    assert "only if `features/` exists" in text and "Divergência por degrau" in text
    for keep in ("--promote", "Drift Summary", "since-plan"):
        assert keep in text


def test_skill_edits_are_forbidden_phrase_free_and_stay_small():
    for parts in (("reflect", "SKILL.md"), ("explain", "SKILL.md"), ("_internal", "explain", "drift", "SKILL.md")):
        text = skill_text(*parts)
        assert "Divergência por degrau" in text or "ladder" in text


# ---- Step 9 findings: the citizen's judgement of the retranslation is its own object

def test_retranslation_judgement_is_not_counted_as_scenario_audit(tmp_path):
    root = copy_tree(_FIX / "retraducao-pos-codigo", tmp_path / "p")
    audit = root / "features" / SLUG / "drift" / "audit.json"
    audit.parent.mkdir(parents=True, exist_ok=True)
    audit.write_text(json.dumps({"schema_version": 1, "itens": [
        {"req": f"REQ-{SLUG}-002", "adequado": "nao", "por": "humano", "objeto": "retraducao",
         "nota": "Não é isso: eu queria no topo."}]}), encoding="utf-8")
    rep = dr.generate(root, SLUG, moment="M1", status_fn=stub_status)
    assert (rep["auditoria"]["nao"], rep["auditoria"]["sim"]) == (0, 0)
    item = next(i for i in rep["retraducao"]["itens"] if i["req"].endswith("002"))
    assert (item["julgamento"], item["nota"]) == ("nao", "Não é isso: eu queria no topo.")
    assert "Você disse: não é isso." in dr.render_citizen(rep)
    assert "Há requisitos em que o cenário não captura" not in dr.render_citizen(rep)
    assert "Julgamento do citizen sobre REQ-contas-da-semana-002: não é isso" in dr.render_markdown(rep)
